---
name: "ASPM-RUNNER-ACCOUNT-1"
"on":
  pull_request:
    branches:
    - "master"
    types:
    - "opened"
    - "synchronize"
    - "reopened"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "info"
jobs:
  scanning:
    env:
      workdir: "${{ github.workspace }}/wrkdir"
    steps:
    - uses: "actions/checkout@v4"
      with:
        path: "${{ env.workdir }}/src"
    - name: "Configure AWS credentials"
      uses: "aws-actions/configure-aws-credentials@v4"
      with:
        aws-access-key-id: "${{ secrets.AWS_ACCESS_KEY_ID }}"
        aws-secret-access-key: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        aws-session-token: "${{ secrets.AWS_SESSION_TOKEN }}"
        aws-region: "us-west-2"
    - name: "Download Scanner"
      run: "aws s3 cp s3://securin-qa-shiftleft/scanners/securin-cli/2.0.1/securin-runner\
        \ ${{ env.workdir }}/src/ASPMRunner && chmod +x ${{ env.workdir }}/src/ASPMRunner"
    - name: "Run Scan"
      run: "./ASPMRunner --api_key df587299f15b01f64e5886c2308f8ad95cb50d755758cb7e2e41d1990c6b7180\
        \ --connector_id 1234 --account_id 1"
      working-directory: "${{ env.workdir }}/src"
    - name: "Upload Results"
      uses: "actions/upload-artifact@v4"
      with:
        name: "scan-results"
        path: "${{ env.workdir }}/results"
      if: "always()"
    runs-on: "ubuntu-latest"
