---
name: "ASPM-RUNNER-ACCOUNT-1"
"on":
  pull_request:
    branches:
    - "master"
    types:
    - "opened"
    - "synchronize"
    - "reopened"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "info"
jobs:
  scanning:
    env:
      workdir: "${{ github.workspace }}/wrkdir"
    steps:
    - uses: "actions/checkout@v4"
    - name: "Configure AWS credentials"
      uses: "aws-actions/configure-aws-credentials@v4"
    - name: "Download Scanner"
      run: "aws s3 cp s3://securin-qa-shiftleft/scanners/securin-cli/2.0.1/securin-runner\
        \ ${{ env.workdir }}/src/ASPMRunner && chmod +x ${{ env.workdir }}/src/ASPMRunner"
    - name: "Run Scan"
      run: "./ASPMRunner --connector_id 1234 --account_id 1"
    - name: "Upload Results"
      uses: "actions/upload-artifact@v4"
      if: "always()"
    runs-on: "ubuntu-latest"
